package org.vaadin.rating.service.data;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Entity
public class Comment {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    @NotNull @Lob
    private String comment = "";
    @NotNull
    @Temporal(TemporalType.TIMESTAMP)
    private Date timeGiven = new Date();
    @NotNull
    private String email;
    @ManyToOne
    private Presentation presentation;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getTimeGiven() {
        return timeGiven;
    }

    public void setTimeGiven(Date timeGiven) {
        this.timeGiven = timeGiven;
    }

    public Presentation getPresentation() {
        return presentation;
    }

    public void setPresentation(Presentation presentation) {
        this.presentation = presentation;
    }
}
