package org.vaadin.rating.service.data;

import com.vaadin.annotations.AutoGenerated;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
public class Rating {

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    private double rating; // 1-5 stars
    @NotNull
    private String email;
    @NotNull
    @ManyToOne
    private Presentation presentation;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getRating() {
        return rating;
    }

    public void setRating(double rating) {
        this.rating = rating;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Presentation getPresentation() {
        return presentation;
    }

    public void setPresentation(Presentation presentation) {
        this.presentation = presentation;
    }
}
